language: go

install:
  - go get github.com/mattn/goveralls

script: 
    - go test -run . -v -covermode=count -coverprofile=coverage.out
    - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
